/**
 * @file application.h
 * @brief Application starting point.
 * @copyright (c) 2020 TOPTICA Photonics AG
 * @author Xiaodong Zhang <xiaodong.zhang@toptica.com>
 * @date 2020-02-04
 */
#pragma once
#include <tsp/pid.hpp>
#ifdef __cplusplus
extern "C" {
#endif

/**
 * @brief Starting point for the application.
 *
 * This function is called from the `main` function generated by STM's CubeMX.
 */
void application();
void application_interupt();
void control_test();

#ifdef __cplusplus
}
#endif
